# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'uteroo_ios' do
  use_frameworks!

  # Pods for uteroo_ios
   pod 'FSCalendar'

  target 'uteroo_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'uteroo_iosUITests' do
    # Pods for testing
  end

end
